### PR TITLE
Add a files module to assist with finding files associated a plot.

### PR DESCRIPTION
**Pull request by jterstriep**
Added a new files module that assists with locating the which sensor files are associated with plot boundaries by querying and merging queries to geostreams api and clowder api.

The primary function is get_file_listing that takes a sensor name (ie 'Thermal IR GeoTIFFs Datasets') and sitename (ie 'MAC Field Scanner Season 1 Field Plot 101 W') and returns a list of all the files in the all the matching datasets. A utility function turns this into a list of absolute file paths.

A couple of notes -
* I tried to make the function signature look like other functions in terrautils. 
* There is probably some overlap with functions available elsewhere but serious refactoring is needed. 
* Use classes!

### CODE REVIEW

**Comment by Paheding** [comment]
@jterstriep I am wondering if there is any document or instruction available so that I can follow to review and use this module.  And which online platform (e.g., Workbench ) would be the best to use this module? Thanks.

**Comment by jterstriep** [comment]
There is a 'products' branch in the tutorials repository that shows basic usage. I have submitted the pull request yet but you can see the basic usage there.

**Comment by Paheding** [comment]
@jterstriep I have reviewed and approved documents. I am wondering if it is possible to run the functions and get the outputs from a local computer by installing those dependencies?

**Comment by dlebauer** [comment]
@Paheding have you tried running this locally? What exact code did you try and what errors did you run into?

**Comment by Paheding** [comment]
I have tried in Workbench Jupyter Python, but it did not work, it says "No module named 'terrautils'. I guess this is due to the module has not yet been installed in the Workbench yet. 
I will try it locally to see if it works. If there is a specific document to describe the usage in different coding environment would be helpful.

**Pull request merged**
